Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
S = firm.solve()
S.head()
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mAttributeError[0m                            Traceback (most recent call last)
Input [1;32mIn [12][0m, in [0;36m<cell line: 1>[1;34m()[0m
[1;32m----> 1[0m S [38;5;241m=[39m [43mfirm[49m[38;5;241;43m.[39;49m[43msolve[49m[43m([49m[43m)[49m
[0;32m      2[0m S[38;5;241m.[39mhead()

File [1;32mC:\ProgramData\Anaconda3\lib\site-packages\compecon\dpmodel.py:458[0m, in [0;36mDPmodel.solve[1;34m(self, v, x, nr, **kwargs)[0m
[0;32m    456[0m     [38;5;28mself[39m[38;5;241m.[39m__solve_by_function_iteration()
[0;32m    457[0m [38;5;28;01melif[39;00m [38;5;28mself[39m[38;5;241m.[39moptions[38;5;241m.[39malgorithm [38;5;241m==[39m [38;5;124m'[39m[38;5;124mnewton[39m[38;5;124m'[39m:
[1;32m--> 458[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m__solve_by_Newton_method[49m[43m([49m[43m)[49m
[0;32m    459[0m [38;5;28;01melse[39;00m:
[0;32m    460[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124m'[39m[38;5;124mUnknown solution algorithm[39m[38;5;124m'[39m)

File [1;32mC:\ProgramData\Anaconda3\lib\site-packages\compecon\dpmodel.py:829[0m, in [0;36mDPmodel.__solve_by_Newton_method[1;34m(self)[0m
[0;32m    827[0m cold [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mValue[38;5;241m.[39mc[38;5;241m.[39mcopy()[38;5;241m.[39mflatten()
[0;32m    828[0m [38;5;66;03m# print('\ncold', cold)[39;00m
[1;32m--> 829[0m [38;5;28mself[39m[38;5;241m.[39mValue_j[:], vc [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mvmax[49m[43m([49m[43ms[49m[43m,[49m[43m [49m[43mx[49m[43m,[49m[43m [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mValue[49m[43m,[49m[43m [49m[38;5;28;43;01mTrue[39;49;00m[43m)[49m
[0;32m    830[0m [38;5;28mself[39m[38;5;241m.[39mmake_discrete_choice()
[0;32m    831[0m step [38;5;241m=[39m [38;5;241m-[39m SOLVE(Phik [38;5;241m-[39m vc, Phik [38;5;241m@[39m cold [38;5;241m-[39m [38;5;28mself[39m[38;5;241m.[39mValue[38;5;241m.[39my[38;5;241m.[39mflatten())

File [1;32mC:\ProgramData\Anaconda3\lib\site-packages\compecon\dpmodel.py:896[0m, in [0;36mDPmodel.vmax[1;34m(self, s, x, Value, dVc)[0m
[0;32m    894[0m                         snext [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mtransition(s[:, is_], x[i, j, :, is_], i , j, in_, ee[:, is_])  [38;5;66;03m#fixme need to know number of output arguments!!![39;00m
[0;32m    895[0m                         prob [38;5;241m=[39m w[k] [38;5;241m*[39m q[j, i, in_,]
[1;32m--> 896[0m                         vc[is_, i, :, in_] [38;5;241m+[39m[38;5;241m=[39m prob [38;5;241m*[39m [43mValue[49m[38;5;241;43m.[39;49m[43mPhi[49m[43m([49m[43msnext[49m[43m)[49m[38;5;241;43m.[39;49m[43mtoarray[49m()[38;5;241m.[39mreshape((is_[38;5;241m.[39msum(), ms), order[38;5;241m=[39m[38;5;124m'[39m[38;5;124mF[39m[38;5;124m'[39m)   [38;5;66;03m#fixme I can't find the proper way to index this[39;00m
[0;32m    898[0m     vc [38;5;241m=[39m vc[38;5;241m.[39mreshape((ns[38;5;241m*[39mni,ms[38;5;241m*[39mni),order[38;5;241m=[39m[38;5;124m'[39m[38;5;124mF[39m[38;5;124m'[39m)
[0;32m    899[0m [38;5;28;01melse[39;00m:

[1;31mAttributeError[0m: 'numpy.ndarray' object has no attribute 'toarray'
AttributeError: 'numpy.ndarray' object has no attribute 'toarray'

